apiVersion: v1
kind: Service
metadata:
  name: stk-svc
spec:
  selector:
    app: stk
  ports:
    - protocol: UDP
      port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stk
  name: stk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stk
  template:
    metadata:
      labels:
        app: stk
    spec:
      shareProcessNamespace: true
      containers:
      - name: stk
        env:
        - name: UDP_SOCKET_PORT
          value: "8081"
        - name: UDP_SOCKET_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: 823260657877.dkr.ecr.us-west-2.amazonaws.com/stk:20221117031035
        imagePullPolicy: Always
        command: ["/stk-code/start-server.sh"]
        ports:
          - name: udp
            containerPort: 8081
            protocol: UDP
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        resources:
          requests:
            cpu: 1024m
            memory: 1024Mi
